const mongoose = require("mongoose");
const dotenv = require("dotenv");
const connectDB = require("./src/config/db"); // Import database connection
const Product = require("./src/models/product"); // Import Product model

dotenv.config(); // Load .env variables

const insertProducts = async () => {
  try {
    await connectDB(); // Connect to MongoDB

    // Delete existing products
    await Product.deleteMany({});
    console.log("Existing products deleted");

    // Product Data
    const products = [
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742135705/1_eeazoj.jpg",
        name: "Stylish Cotton T-Shirt - Multiple Colors",
        categories: ["Clothing", "Summer Clothes", "Casual Wear"],
        currentPrice: 22.0,
        bulkPricing: [
          { minQuantity: 50, maxQuantity: 100, price: 22.0 },
          { minQuantity: 101, maxQuantity: 500, price: 20.0 },
          { minQuantity: 501, maxQuantity: null, price: 18.0 },
        ],
        previousPrice: 30.0,
        tax: 1.5,
        rating: 4.0,
        reviews: 20,
        orders: 120,
        stock: 33,
        shipping: "Free Shipping",
        description:
          "Soft and comfortable cotton T-shirt available in multiple colors.",
        type: "Casual Wear",
        material: "Cotton",
        sizes: ["Small", "Medium", "Large", "XL"],
        customization: "Custom logo and design available",
        protection: "Refund Policy",
        warranty: "1 year warranty",
        supplier: {
          name: "Guanjoi Trading LLC",
          location: "Istanbul, Turkiye",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742135706/2_dhu79t.jpg",
        name: "Unisex Blue T-Shirt - Premium Fabric",
        categories: ["Clothing", "Casual Wear", "Summer Clothes"],
        currentPrice: 29.9,
        bulkPricing: [
          { minQuantity: 30, maxQuantity: 80, price: 28.0 },
          { minQuantity: 81, maxQuantity: 300, price: 26.5 },
          { minQuantity: 301, maxQuantity: null, price: 25.0 },
        ],
        previousPrice: 35.0,
        tax: 2.0,
        rating: 4.2,
        reviews: 85,
        orders: 85,
        stock: 25,
        shipping: "Free Shipping",
        description:
          "High-quality unisex T-shirt in blue with premium breathable fabric.",
        type: "Casual Wear",
        material: "Cotton Blend",
        sizes: ["Small", "Medium", "Large", "XL"],
        customization: "Available for bulk orders",
        protection: "Money-back guarantee",
        warranty: "6 months warranty",
        supplier: {
          name: "Jiangsu Textile Ltd.",
          location: "Shanghai, China",
          verified: false,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742135706/3_w92af7.jpg",
        name: "Casual Winter Jacket - Brown Color",
        categories: ["Clothing", "Winter Wear", "Outerwear"],
        currentPrice: 290.5,
        bulkPricing: [
          { minQuantity: 10, maxQuantity: 50, price: 750.0 },
          { minQuantity: 51, maxQuantity: 200, price: 720.0 },
          { minQuantity: 201, maxQuantity: null, price: 700.0 },
        ],
        previousPrice: 340.0,
        tax: 15.0,
        rating: 4.8,
        reviews: 60,
        orders: 60,
        stock: 0,
        shipping: "Free Shipping",
        description:
          "Stylish brown winter jacket with cozy interior for warmth and comfort.",
        type: "Winter Wear",
        material: "Faux Leather & Fleece",
        sizes: ["Medium", "Large", "XL"],
        customization: "Custom embroidery available",
        protection: "Quality assurance guarantee",
        warranty: "2 years warranty",
        supplier: {
          name: "Arctic Gear Inc.",
          location: "Toronto, Canada",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742139013/5_duy6wi.jpg",
        name: "Gaming Headset with Microphone",
        categories: ["Tech", "Electronics", "Gaming Accessories", "Headsets"],
        currentPrice: 98.95,
        bulkPricing: [
          { minQuantity: 20, maxQuantity: 100, price: 95.0 },
          { minQuantity: 101, maxQuantity: 300, price: 90.0 },
          { minQuantity: 301, maxQuantity: null, price: 85.0 },
        ],
        previousPrice: 149.99,
        tax: 8.0,
        rating: 5.0,
        reviews: 61,
        orders: 61,
        stock: 20,
        shipping: "Free Shipping",
        description:
          "High-quality gaming headset with noise cancellation and a built-in mic.",
        type: "Gaming Headphone",
        material: "Plastic & Memory Foam",
        customization: "Logo printing available",
        protection: "Warranty claim available",
        warranty: "1-year manufacturer warranty",
        supplier: {
          name: "TechSound Electronics",
          location: "Berlin, Germany",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742135702/4_ffe3jy.jpg",
        name: "Interior Plant with Natural Vase",
        categories: ["Interiors", "Home Decor", "Plants"],
        currentPrice: 20,
        bulkPricing: [
          { minQuantity: 10, maxQuantity: 50, price: 65.0 },
          { minQuantity: 51, maxQuantity: 150, price: 60.0 },
          { minQuantity: 151, maxQuantity: null, price: 55.0 },
        ],
        previousPrice: 25,
        tax: 1.5,
        rating: 3.2,
        reviews: 61,
        orders: 61,
        stock: 5,
        shipping: "Free Shipping",
        description:
          "Beautiful indoor plant with a stylish natural vase for home decor.",
        type: "Home Decor",
        material: "Ceramic & Plant",
        customization: "Pot color customization available",
        protection: "Damage replacement policy",
        warranty: "3-month plant health warranty",
        supplier: {
          name: "GreenLife Nurseries",
          location: "California, USA",
          verified: true,
          worldwideShipping: false,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742139014/6_h1qmnk.jpg",
        name: "GoPro HERO6 4K Action Camera - Black",
        categories: ["Tech", "Electronics", "Cameras", "Action Cameras"],
        currentPrice: 999.0,
        bulkPricing: [
          { minQuantity: 5, maxQuantity: 20, price: 95.0 },
          { minQuantity: 21, maxQuantity: 50, price: 90.0 },
          { minQuantity: 51, maxQuantity: null, price: 85.0 },
        ],
        previousPrice: 1128.0,
        tax: 25.0,
        rating: 4.2,
        reviews: 75,
        orders: 75,
        stock: 2,
        shipping: "Free Shipping",
        description:
          "High-performance 4K action camera for adventure and sports recording.",
        type: "Camera",
        material: "Plastic & Metal",
        customization: "Brand logo engraving available",
        protection: "1-month replacement policy",
        warranty: "1-year international warranty",
        supplier: {
          name: "ActionCam Ltd.",
          location: "Tokyo, Japan",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742135701/1_qdwtem.jpg",
        name: "Office Chair Soft Material - Light Cream Color",
        categories: ["Interiors", "Office Furniture", "Home Decor"],
        currentPrice: 250.0,
        bulkPricing: [
          { minQuantity: 5, maxQuantity: 20, price: 370.0 },
          { minQuantity: 21, maxQuantity: 100, price: 350.0 },
        ],
        previousPrice: null,
        tax: 10.5,
        rating: 3.5,
        reviews: 61,
        orders: 61,
        stock: 6,
        shipping: "Free Shipping",
        description:
          "Ergonomic office chair with soft cushioning for long hours of comfort.",
        type: "Office Furniture",
        material: "Leather & Metal",
        sizes: ["One Size"],
        customization: "Available in multiple colors",
        protection: "Warranty Coverage",
        warranty: "2 years",
        supplier: {
          name: "Comfort Chairs Ltd.",
          location: "Berlin, Germany",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742135701/2_bcbhk6.jpg",
        name: "Ergonomic Office Chair - Adjustable Height",
        categories: [
          "Furniture",
          "Office Chairs",
          "Ergonomic Seating",
          "Interiors",
        ],
        currentPrice: 120.0,
        bulkPricing: [
          { minQuantity: 10, maxQuantity: 50, price: 18.0 },
          { minQuantity: 51, maxQuantity: 200, price: 16.0 },
          { minQuantity: 201, maxQuantity: null, price: 14.0 },
        ],
        previousPrice: 150.0,
        tax: 7.5,
        rating: 4.3,
        reviews: 15,
        orders: 85,
        stock: 40,
        shipping: "Free Shipping",
        description:
          "Comfortable office chair with ergonomic design and adjustable height.",
        type: "Office Furniture",
        material: "Mesh & Metal",
        sizes: ["Standard", "Large"],
        customization: "Custom color and branding available",
        protection: "Refund Policy",
        warranty: "2 years warranty",
        supplier: {
          name: "Office Solutions Ltd.",
          location: "Berlin, Germany",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742135702/3_yisbza.jpg",
        name: "Ceramic Kitchen Dish Set - 6 Pieces",
        categories: ["Kitchen", "Dinnerware", "Ceramic Dishes", "Interiors"],
        currentPrice: 7.0,
        bulkPricing: [
          { minQuantity: 20, maxQuantity: 100, price: 6.5 },
          { minQuantity: 101, maxQuantity: 500, price: 6.0 },
          { minQuantity: 501, maxQuantity: null, price: 5.5 },
        ],
        previousPrice: 10.0,
        tax: 1.0,
        rating: 4.5,
        reviews: 22,
        orders: 120,
        stock: 60,
        shipping: "Free Shipping",
        description:
          "Elegant ceramic dish set with a modern design, perfect for any kitchen.",
        type: "Dinnerware",
        material: "Ceramic",
        sizes: ["Small", "Medium", "Large"],
        customization: "Custom logo available",
        protection: "Breakage Protection",
        warranty: "1 year warranty",
        supplier: {
          name: "Fine Dine Co.",
          location: "Paris, France",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742135702/5_ezydth.jpg",
        name: "Luxury Bedroom Set - Wooden Frame",
        categories: ["Furniture", "Bedroom", "Home Decor", "Interiors"],
        currentPrice: 80.0,
        bulkPricing: [
          { minQuantity: 5, maxQuantity: 20, price: 11.0 },
          { minQuantity: 21, maxQuantity: 100, price: 10.0 },
          { minQuantity: 101, maxQuantity: null, price: 9.0 },
        ],
        previousPrice: 100.0,
        tax: 6.0,
        rating: 4.6,
        reviews: 18,
        orders: 90,
        stock: 25,
        shipping: "Free Shipping",
        description:
          "Elegant wooden bedroom set with a stylish modern finish for home decor.",
        type: "Home Furniture",
        material: "Solid Wood",
        sizes: ["Single", "Queen", "King"],
        customization: "Custom wood finish available",
        protection: "Damage Protection",
        warranty: "5 years warranty",
        supplier: {
          name: "Luxury Living Inc.",
          location: "Milan, Italy",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742135702/6_iuv8yc.jpg",
        name: "Modern Home Lighting - LED Ceiling Lamp",
        categories: ["Lighting", "Home Decor", "LED Lights", "Interiors"],
        currentPrice: 19.0,
        bulkPricing: [
          { minQuantity: 10, maxQuantity: 50, price: 18.0 },
          { minQuantity: 51, maxQuantity: 200, price: 16.5 },
          { minQuantity: 201, maxQuantity: null, price: 15.0 },
        ],
        previousPrice: 25.0,
        tax: 2.0,
        rating: 4.4,
        reviews: 30,
        orders: 140,
        stock: 50,
        shipping: "Free Shipping",
        description:
          "Elegant LED ceiling lamp, perfect for home lighting and energy-efficient.",
        type: "Home Lighting",
        material: "Aluminum & Glass",
        sizes: ["Small", "Medium", "Large"],
        customization: "Custom color and design available",
        protection: "Refund Policy",
        warranty: "2 years warranty",
        supplier: {
          name: "BrightGlow Lighting Co.",
          location: "Shenzhen, China",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742135702/7_dqr1fv.jpg",
        name: "Leather Magazine Holder - Brown",
        categories: [
          "Furniture",
          "Office Decor",
          "Home Accessories",
          "Interiors",
        ],
        currentPrice: 35.0,
        bulkPricing: [
          { minQuantity: 10, maxQuantity: 50, price: 32.0 },
          { minQuantity: 51, maxQuantity: 200, price: 30.0 },
          { minQuantity: 201, maxQuantity: null, price: 28.0 },
        ],
        previousPrice: 45.0,
        tax: 3.0,
        rating: 4.6,
        reviews: 75,
        orders: 150,
        stock: 60,
        shipping: "Free Shipping",
        description: "Elegant leather magazine holder for home and office use.",
        type: "Home Decor",
        material: "Leather & Metal",
        sizes: ["Standard"],
        customization: "Custom colors available",
        protection: "Refund Policy",
        warranty: "1 year warranty",
        supplier: {
          name: "Elite Home Furnishings",
          location: "Berlin, Germany",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742135702/8_wpyedw.jpg",
        name: "Bosch Automatic Coffee Machine",
        categories: [
          "Kitchen Appliances",
          "Electronics",
          "Coffee Makers",
          "Interiors",
        ],
        currentPrice: 120.0,
        bulkPricing: [
          { minQuantity: 10, maxQuantity: 50, price: 115.0 },
          { minQuantity: 51, maxQuantity: 200, price: 110.0 },
          { minQuantity: 201, maxQuantity: null, price: 105.0 },
        ],
        previousPrice: 150.0,
        tax: 10.0,
        rating: 4.8,
        reviews: 180,
        orders: 300,
        stock: 40,
        shipping: "Free Shipping",
        description: "Automatic coffee machine with multiple brewing options.",
        type: "Kitchen Appliance",
        material: "Plastic & Stainless Steel",
        sizes: ["Standard"],
        customization: "Custom branding available",
        protection: "Return Policy",
        warranty: "2 years warranty",
        supplier: {
          name: "Bosch Appliances",
          location: "Munich, Germany",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742139012/3_rsh64i.jpg",
        name: "Xiaomi Mi 9 - Dual Camera Smartphone",
        categories: ["Smartphones", "Electronics", "Mobile Devices", "Tech"],
        currentPrice: 300.0,
        bulkPricing: [
          { minQuantity: 10, maxQuantity: 50, price: 290.0 },
          { minQuantity: 51, maxQuantity: 200, price: 280.0 },
          { minQuantity: 201, maxQuantity: null, price: 270.0 },
        ],
        previousPrice: 350.0,
        tax: 25.0,
        rating: 4.6,
        reviews: 500,
        orders: 1200,
        stock: 50,
        shipping: "Free Shipping",
        description:
          "Flagship smartphone with dual-camera setup and high-performance processor.",
        type: "Smartphone",
        material: "Glass & Aluminum",
        sizes: ["6.39-inch Display"],
        customization: "Custom engraving available",
        protection: "Return Policy",
        warranty: "1 year warranty",
        // thumbnails: [
        //   "/tech/smartphone_front.jpg",
        //   "/tech/smartphone_back.jpg",
        //   "/tech/smartphone_side.jpg",
        // ],
        supplier: {
          name: "Xiaomi Official Store",
          location: "Beijing, China",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742139012/4_o88nsk.jpg",
        name: "Apple iPhone 12 - 128GB, Blue",
        categories: ["Smartphones", "Electronics", "Apple", "Tech"],
        currentPrice: 750.0,
        bulkPricing: [
          { minQuantity: 10, maxQuantity: 50, price: 730.0 },
          { minQuantity: 51, maxQuantity: 200, price: 710.0 },
          { minQuantity: 201, maxQuantity: null, price: 690.0 },
        ],
        previousPrice: 850.0,
        tax: 35.0,
        rating: 5.0,
        reviews: 1200,
        orders: 2500,
        stock: 30,
        shipping: "Free Shipping",
        description:
          "Apple iPhone 12 with A14 Bionic chip, 5G, and Super Retina XDR display.",
        type: "Smartphone",
        material: "Aluminum & Glass",
        sizes: ["128GB", "256GB", "512GB"],
        customization: "No customization available",
        protection: "AppleCare+ available",
        warranty: "1 year warranty",
        // thumbnails: [
        //   "/tech/iphone12_front.jpg",
        //   "/tech/iphone12_back.jpg",
        //   "/tech/iphone12_side.jpg",
        // ],
        supplier: {
          name: "Apple Official Store",
          location: "Cupertino, USA",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742139014/7_jjpj8e.jpg",
        name: "High-Performance Ultrabook",
        categories: ["Laptops", "Electronics", "Computers", "Tech"],
        currentPrice: 1200.0,
        bulkPricing: [
          { minQuantity: 5, maxQuantity: 20, price: 1150.0 },
          { minQuantity: 21, maxQuantity: 100, price: 1100.0 },
          { minQuantity: 101, maxQuantity: null, price: 1050.0 },
        ],
        previousPrice: 1400.0,
        tax: 50.0,
        rating: 4.7,
        reviews: 250,
        orders: 500,
        stock: 25,
        shipping: "Free Shipping",
        description:
          "Premium ultrabook with a high-resolution display and powerful performance.",
        type: "Laptop",
        material: "Aluminum",
        sizes: ["13-inch", "15-inch", "17-inch"],
        customization: "Company logo engraving available",
        protection: "Return Policy",
        warranty: "2 years warranty",
        // thumbnails: [
        //   "/tech/laptop_front.jpg",
        //   "/tech/laptop_side.jpg",
        //   "/tech/laptop_back.jpg",
        // ],
        supplier: {
          name: "TechWorld Ltd.",
          location: "Shenzhen, China",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742139015/8_cvwab9.jpg",
        name: "Smartwatch - Fitness & Health Tracking",
        categories: ["Electronics", "Wearable Tech", "Smartwatches", "Tech"],
        currentPrice: 18.0,
        bulkPricing: [
          { minQuantity: 10, maxQuantity: 50, price: 18.0 },
          { minQuantity: 51, maxQuantity: 200, price: 17.0 },
          { minQuantity: 201, maxQuantity: null, price: 15.0 },
        ],
        previousPrice: 25.0,
        tax: 2.0,
        rating: 4.4,
        reviews: 180,
        orders: 350,
        stock: 80,
        shipping: "Free Shipping",
        description:
          "Smartwatch with fitness tracking, heart rate monitor, and notifications.",
        type: "Wearable",
        material: "Silicone & Aluminum",
        sizes: ["Small", "Medium", "Large"],
        customization: "Custom watch faces available",
        protection: "Refund Policy",
        warranty: "1 year warranty",
        supplier: {
          name: "FutureTech Gadgets",
          location: "Shenzhen, China",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742139016/9_jznvzr.jpg",
        name: "Wireless Headphone - Noise Cancelling",
        categories: ["Electronics", "Audio", "Headphones", "Tech"],
        currentPrice: 15.0,
        bulkPricing: [
          { minQuantity: 10, maxQuantity: 50, price: 18.5 },
          { minQuantity: 51, maxQuantity: 200, price: 17.5 },
          { minQuantity: 201, maxQuantity: null, price: 16.0 },
        ],
        previousPrice: 30.0,
        tax: 2.0,
        rating: 2.9,
        reviews: 250,
        orders: 400,
        stock: 50,
        shipping: "Free Shipping",
        description:
          "Wireless Bluetooth headphones with active noise cancellation.",
        type: "Headphone",
        material: "Plastic & Leather",
        sizes: ["One Size"],
        customization: "Custom branding available",
        protection: "Money-Back Guarantee",
        warranty: "2 years warranty",
        supplier: {
          name: "SoundWave Audio Ltd.",
          location: "Berlin, Germany",
          verified: false,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742139011/10_na6rot.jpg",
        name: "Electric Kettle - Fast Boil",
        categories: [
          "Home Appliances",
          "Kitchen",
          "Electric Kettle",
          "Tech",
          "Kitchen Appliances",
        ],
        currentPrice: 25.0,
        bulkPricing: [
          { minQuantity: 10, maxQuantity: 50, price: 18.0 },
          { minQuantity: 51, maxQuantity: 200, price: 17.0 },
          { minQuantity: 201, maxQuantity: null, price: 15.0 },
        ],
        previousPrice: 30.0,
        tax: 2.0,
        rating: 4.5,
        reviews: 130,
        orders: 270,
        stock: 65,
        shipping: "Free Shipping",
        description:
          "Electric kettle with fast boil technology and auto shut-off.",
        type: "Kitchen Appliance",
        material: "Stainless Steel",
        sizes: ["1L", "1.5L", "2L"],
        customization: "Custom logo available",
        protection: "Return Policy",
        warranty: "1 year warranty",
        supplier: {
          name: "HomeTech Solutions",
          location: "Istanbul, Turkiye",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742135707/4_kfrirx.jpg",
        name: "Men's Dark Blue Jeans Shorts",
        categories: ["Clothing", "Men's Fashion", "Casual Wear"],
        currentPrice: 12.0,
        bulkPricing: [
          { minQuantity: 10, maxQuantity: 50, price: 11.0 },
          { minQuantity: 51, maxQuantity: 200, price: 10.0 },
          { minQuantity: 201, maxQuantity: null, price: 9.0 },
        ],
        previousPrice: 15.0,
        tax: 1.0,
        rating: 3.9,
        reviews: 90,
        orders: 200,
        stock: 70,
        shipping: "Free Shipping",
        description:
          "Comfortable dark blue denim shorts for men, perfect for summer.",
        type: "Casual Wear",
        material: "Denim",
        sizes: ["S", "M", "L", "XL"],
        customization: "Custom fit available",
        protection: "Money-Back Guarantee",
        warranty: "6 months warranty",
        supplier: {
          name: "Urban Denim Co.",
          location: "Los Angeles, USA",
          verified: false,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742135707/5_xgbeo8.jpg",
        name: "Lightweight Jeans Bag for Travel - Unisex",
        categories: ["Accessories", "Bags", "Travel Gear"],
        currentPrice: 192.5,
        bulkPricing: [
          { minQuantity: 5, maxQuantity: 20, price: 185.0 },
          { minQuantity: 21, maxQuantity: 100, price: 175.0 },
          { minQuantity: 101, maxQuantity: null, price: 165.0 },
        ],
        previousPrice: 220.0,
        tax: 20.0,
        rating: 4.6,
        reviews: 150,
        orders: 320,
        stock: 40,
        shipping: "Free Shipping",
        description:
          "Durable and lightweight jeans fabric travel bag, suitable for both men and women.",
        type: "Travel Bag",
        material: "Denim & Polyester",
        sizes: ["Small", "Medium", "Large"],
        customization: "Custom logo and name engraving available",
        protection: "Return Policy",
        warranty: "2 years warranty",
        supplier: {
          name: "Nomad Gear Co.",
          location: "Istanbul, Turkiye",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742135709/6_hkbhlw.jpg",
        name: "Classic Leather Wallet - Blue",
        categories: ["Accessories", "Wallets", "Men's Fashion"],
        currentPrice: 29.99,
        bulkPricing: [
          { minQuantity: 10, maxQuantity: 50, price: 27.5 },
          { minQuantity: 51, maxQuantity: 200, price: 25.0 },
          { minQuantity: 201, maxQuantity: null, price: 22.0 },
        ],
        previousPrice: 35.0,
        tax: 2.5,
        rating: 4.5,
        reviews: 85,
        orders: 250,
        stock: 80,
        shipping: "Free Shipping",
        description: "Premium quality leather wallet in a stylish blue color.",
        type: "Wallet",
        material: "Genuine Leather",
        sizes: ["Standard"],
        customization: "Custom engraving available",
        protection: "Money-Back Guarantee",
        warranty: "1 year warranty",
        supplier: {
          name: "Elite Accessories Co.",
          location: "Milan, Italy",
          verified: true,
          worldwideShipping: true,
        },
      },
      {
        image:
          "https://res.cloudinary.com/db7jmsq76/image/upload/v1742135707/7_tbximq.jpg",
        name: "Men's Formal Blue Suit Jacket",
        categories: ["Clothing", "Formal Wear", "Men's Fashion"],
        currentPrice: 120.0,
        bulkPricing: [
          { minQuantity: 10, maxQuantity: 50, price: 115.0 },
          { minQuantity: 51, maxQuantity: 200, price: 110.0 },
          { minQuantity: 201, maxQuantity: null, price: 100.0 },
        ],
        previousPrice: 150.0,
        tax: 15.0,
        rating: 4.7,
        reviews: 120,
        orders: 180,
        stock: 50,
        shipping: "Free Shipping",
        description:
          "Elegant and stylish blue suit jacket for formal occasions.",
        type: "Formal Wear",
        material: "Polyester & Cotton Blend",
        sizes: ["S", "M", "L", "XL"],
        customization: "Custom fitting available",
        protection: "Return Policy",
        warranty: "1 year warranty",
        supplier: {
          name: "Elegant Suits Ltd.",
          location: "London, UK",
          verified: true,
          worldwideShipping: true,
        },
      },
    ];

    // Insert New Products
    await Product.insertMany(products);
    console.log("Products inserted successfully!");

    // Close MongoDB Connection
    mongoose.connection.close();
  } catch (error) {
    console.error("Error inserting products:", error);
    process.exit(1);
  }
};

// Run the function
insertProducts();
